//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.01 at 02:40:24 PM PDT 
//


package com.poc.demo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for colSchemaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="colSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{}dataTypeEnumType" />
 *       &lt;attribute name="isKey" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="len" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="codepage" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beforeColName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "colSchemaType")
public class ColSchemaType {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected DataTypeEnumType type;
    @XmlAttribute(name = "isKey")
    protected Boolean isKey;
    @XmlAttribute(name = "len")
    @XmlSchemaType(name = "unsignedInt")
    protected Long len;
    @XmlAttribute(name = "precision")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer precision;
    @XmlAttribute(name = "scale")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer scale;
    @XmlAttribute(name = "codepage")
    @XmlSchemaType(name = "unsignedInt")
    protected Long codepage;
    @XmlAttribute(name = "default")
    protected String _default;
    @XmlAttribute(name = "beforeColName")
    protected String beforeColName;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypeEnumType }
     *     
     */
    public DataTypeEnumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypeEnumType }
     *     
     */
    public void setType(DataTypeEnumType value) {
        this.type = value;
    }

    /**
     * Gets the value of the isKey property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsKey() {
        if (isKey == null) {
            return false;
        } else {
            return isKey;
        }
    }

    /**
     * Sets the value of the isKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsKey(Boolean value) {
        this.isKey = value;
    }

    /**
     * Gets the value of the len property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLen() {
        return len;
    }

    /**
     * Sets the value of the len property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLen(Long value) {
        this.len = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrecision(Integer value) {
        this.precision = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScale(Integer value) {
        this.scale = value;
    }

    /**
     * Gets the value of the codepage property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getCodepage() {
        if (codepage == null) {
            return  0L;
        } else {
            return codepage;
        }
    }

    /**
     * Sets the value of the codepage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCodepage(Long value) {
        this.codepage = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * Gets the value of the beforeColName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeColName() {
        return beforeColName;
    }

    /**
     * Sets the value of the beforeColName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeColName(String value) {
        this.beforeColName = value;
    }

}
