//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.01 at 02:40:24 PM PDT 
//


package com.poc.demo.pojo;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for lobType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lobType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="blob">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>blob">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="clob">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>clob">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dbclob">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>dbclob">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}commonAttrGroup"/>
 *       &lt;attribute name="isLast" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="colName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rowNum" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="totalDataLen" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="dataLen" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lobType", propOrder = {
    "blob",
    "clob",
    "dbclob"
})
public class LobType {

    @XmlElementRef(name = "blob", type = JAXBElement.class, required = false)
    protected JAXBElement<LobType.Blob> blob;
    @XmlElementRef(name = "clob", type = JAXBElement.class, required = false)
    protected JAXBElement<LobType.Clob> clob;
    @XmlElementRef(name = "dbclob", type = JAXBElement.class, required = false)
    protected JAXBElement<LobType.Dbclob> dbclob;
    @XmlAttribute(name = "isLast", required = true)
    protected boolean isLast;
    @XmlAttribute(name = "colName", required = true)
    protected String colName;
    @XmlAttribute(name = "rowNum", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger rowNum;
    @XmlAttribute(name = "totalDataLen", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalDataLen;
    @XmlAttribute(name = "dataLen", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger dataLen;
    @XmlAttribute(name = "subName", required = true)
    protected String subName;
    @XmlAttribute(name = "srcOwner", required = true)
    protected String srcOwner;
    @XmlAttribute(name = "srcName", required = true)
    protected String srcName;
    @XmlAttribute(name = "intentSEQ")
    protected String intentSEQ;

    /**
     * Gets the value of the blob property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LobType.Blob }{@code >}
     *     
     */
    public JAXBElement<LobType.Blob> getBlob() {
        return blob;
    }

    /**
     * Sets the value of the blob property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LobType.Blob }{@code >}
     *     
     */
    public void setBlob(JAXBElement<LobType.Blob> value) {
        this.blob = value;
    }

    /**
     * Gets the value of the clob property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LobType.Clob }{@code >}
     *     
     */
    public JAXBElement<LobType.Clob> getClob() {
        return clob;
    }

    /**
     * Sets the value of the clob property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LobType.Clob }{@code >}
     *     
     */
    public void setClob(JAXBElement<LobType.Clob> value) {
        this.clob = value;
    }

    /**
     * Gets the value of the dbclob property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LobType.Dbclob }{@code >}
     *     
     */
    public JAXBElement<LobType.Dbclob> getDbclob() {
        return dbclob;
    }

    /**
     * Sets the value of the dbclob property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LobType.Dbclob }{@code >}
     *     
     */
    public void setDbclob(JAXBElement<LobType.Dbclob> value) {
        this.dbclob = value;
    }

    /**
     * Gets the value of the isLast property.
     * 
     */
    public boolean isIsLast() {
        return isLast;
    }

    /**
     * Sets the value of the isLast property.
     * 
     */
    public void setIsLast(boolean value) {
        this.isLast = value;
    }

    /**
     * Gets the value of the colName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColName() {
        return colName;
    }

    /**
     * Sets the value of the colName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColName(String value) {
        this.colName = value;
    }

    /**
     * Gets the value of the rowNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRowNum() {
        return rowNum;
    }

    /**
     * Sets the value of the rowNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRowNum(BigInteger value) {
        this.rowNum = value;
    }

    /**
     * Gets the value of the totalDataLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalDataLen() {
        return totalDataLen;
    }

    /**
     * Sets the value of the totalDataLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalDataLen(BigInteger value) {
        this.totalDataLen = value;
    }

    /**
     * Gets the value of the dataLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDataLen() {
        return dataLen;
    }

    /**
     * Sets the value of the dataLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDataLen(BigInteger value) {
        this.dataLen = value;
    }

    /**
     * Gets the value of the subName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubName() {
        return subName;
    }

    /**
     * Sets the value of the subName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubName(String value) {
        this.subName = value;
    }

    /**
     * Gets the value of the srcOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcOwner() {
        return srcOwner;
    }

    /**
     * Sets the value of the srcOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcOwner(String value) {
        this.srcOwner = value;
    }

    /**
     * Gets the value of the srcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcName() {
        return srcName;
    }

    /**
     * Sets the value of the srcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcName(String value) {
        this.srcName = value;
    }

    /**
     * Gets the value of the intentSEQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntentSEQ() {
        return intentSEQ;
    }

    /**
     * Sets the value of the intentSEQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntentSEQ(String value) {
        this.intentSEQ = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>blob">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Blob {

        @XmlValue
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        protected byte[] value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>clob">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Clob {

        @XmlValue
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>dbclob">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Dbclob {

        @XmlValue
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
