//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.01 at 02:40:24 PM PDT 
//


package com.poc.demo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for msgType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="msgType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="trans" type="{}transType"/>
 *         &lt;element name="rowOp" type="{}rowOpType"/>
 *         &lt;element name="subDeactivated" type="{}subDeactivatedType"/>
 *         &lt;element name="loadDoneRcvd" type="{}loadDoneRcvdType"/>
 *         &lt;element name="heartbeat" type="{}heartbeatType"/>
 *         &lt;element name="errorRpt" type="{}errorRptType"/>
 *         &lt;element name="subSchema" type="{}subSchemaType"/>
 *         &lt;element name="lob" type="{}lobType"/>
 *         &lt;element name="addColumn" type="{}addColumnType"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dbName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msgType", propOrder = {
    "trans",
    "rowOp",
    "subDeactivated",
    "loadDoneRcvd",
    "heartbeat",
    "errorRpt",
    "subSchema",
    "lob",
    "addColumn"
})
public class MsgType {

    protected TransType trans;
    protected RowOpType rowOp;
    protected SubDeactivatedType subDeactivated;
    protected LoadDoneRcvdType loadDoneRcvd;
    protected HeartbeatType heartbeat;
    protected ErrorRptType errorRpt;
    protected SubSchemaType subSchema;
    protected LobType lob;
    protected AddColumnType addColumn;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "dbName", required = true)
    protected String dbName;

    /**
     * Gets the value of the trans property.
     * 
     * @return
     *     possible object is
     *     {@link TransType }
     *     
     */
    public TransType getTrans() {
        return trans;
    }

    /**
     * Sets the value of the trans property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransType }
     *     
     */
    public void setTrans(TransType value) {
        this.trans = value;
    }

    /**
     * Gets the value of the rowOp property.
     * 
     * @return
     *     possible object is
     *     {@link RowOpType }
     *     
     */
    public RowOpType getRowOp() {
        return rowOp;
    }

    /**
     * Sets the value of the rowOp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowOpType }
     *     
     */
    public void setRowOp(RowOpType value) {
        this.rowOp = value;
    }

    /**
     * Gets the value of the subDeactivated property.
     * 
     * @return
     *     possible object is
     *     {@link SubDeactivatedType }
     *     
     */
    public SubDeactivatedType getSubDeactivated() {
        return subDeactivated;
    }

    /**
     * Sets the value of the subDeactivated property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubDeactivatedType }
     *     
     */
    public void setSubDeactivated(SubDeactivatedType value) {
        this.subDeactivated = value;
    }

    /**
     * Gets the value of the loadDoneRcvd property.
     * 
     * @return
     *     possible object is
     *     {@link LoadDoneRcvdType }
     *     
     */
    public LoadDoneRcvdType getLoadDoneRcvd() {
        return loadDoneRcvd;
    }

    /**
     * Sets the value of the loadDoneRcvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadDoneRcvdType }
     *     
     */
    public void setLoadDoneRcvd(LoadDoneRcvdType value) {
        this.loadDoneRcvd = value;
    }

    /**
     * Gets the value of the heartbeat property.
     * 
     * @return
     *     possible object is
     *     {@link HeartbeatType }
     *     
     */
    public HeartbeatType getHeartbeat() {
        return heartbeat;
    }

    /**
     * Sets the value of the heartbeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeartbeatType }
     *     
     */
    public void setHeartbeat(HeartbeatType value) {
        this.heartbeat = value;
    }

    /**
     * Gets the value of the errorRpt property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorRptType }
     *     
     */
    public ErrorRptType getErrorRpt() {
        return errorRpt;
    }

    /**
     * Sets the value of the errorRpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorRptType }
     *     
     */
    public void setErrorRpt(ErrorRptType value) {
        this.errorRpt = value;
    }

    /**
     * Gets the value of the subSchema property.
     * 
     * @return
     *     possible object is
     *     {@link SubSchemaType }
     *     
     */
    public SubSchemaType getSubSchema() {
        return subSchema;
    }

    /**
     * Sets the value of the subSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubSchemaType }
     *     
     */
    public void setSubSchema(SubSchemaType value) {
        this.subSchema = value;
    }

    /**
     * Gets the value of the lob property.
     * 
     * @return
     *     possible object is
     *     {@link LobType }
     *     
     */
    public LobType getLob() {
        return lob;
    }

    /**
     * Sets the value of the lob property.
     * 
     * @param value
     *     allowed object is
     *     {@link LobType }
     *     
     */
    public void setLob(LobType value) {
        this.lob = value;
    }

    /**
     * Gets the value of the addColumn property.
     * 
     * @return
     *     possible object is
     *     {@link AddColumnType }
     *     
     */
    public AddColumnType getAddColumn() {
        return addColumn;
    }

    /**
     * Sets the value of the addColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddColumnType }
     *     
     */
    public void setAddColumn(AddColumnType value) {
        this.addColumn = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbName(String value) {
        this.dbName = value;
    }

}
