//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.01 at 02:40:24 PM PDT 
//


package com.poc.demo.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.poc.demo.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Msg_QNAME = new QName("", "msg");
    private final static QName _UpdateValColTypeVargraphicBeforeVal_QNAME = new QName("", "beforeVal");
    private final static QName _SingleValColTypeDate_QNAME = new QName("", "date");
    private final static QName _SingleValColTypeBitvarchar_QNAME = new QName("", "bitvarchar");
    private final static QName _SingleValColTypeDbclob_QNAME = new QName("", "dbclob");
    private final static QName _SingleValColTypeBitchar_QNAME = new QName("", "bitchar");
    private final static QName _SingleValColTypeBitlongvarchar_QNAME = new QName("", "bitlongvarchar");
    private final static QName _SingleValColTypeInteger_QNAME = new QName("", "integer");
    private final static QName _SingleValColTypeFloat_QNAME = new QName("", "float");
    private final static QName _SingleValColTypeRowid_QNAME = new QName("", "rowid");
    private final static QName _SingleValColTypeDecfloat_QNAME = new QName("", "decfloat");
    private final static QName _SingleValColTypeSmallint_QNAME = new QName("", "smallint");
    private final static QName _SingleValColTypeClob_QNAME = new QName("", "clob");
    private final static QName _SingleValColTypeXml_QNAME = new QName("", "xml");
    private final static QName _SingleValColTypeBigint_QNAME = new QName("", "bigint");
    private final static QName _SingleValColTypeGraphic_QNAME = new QName("", "graphic");
    private final static QName _SingleValColTypeTimestamp_QNAME = new QName("", "timestamp");
    private final static QName _SingleValColTypeLongvargraphic_QNAME = new QName("", "longvargraphic");
    private final static QName _SingleValColTypeVargraphic_QNAME = new QName("", "vargraphic");
    private final static QName _SingleValColTypeDouble_QNAME = new QName("", "double");
    private final static QName _SingleValColTypeVarchar_QNAME = new QName("", "varchar");
    private final static QName _SingleValColTypeReal_QNAME = new QName("", "real");
    private final static QName _SingleValColTypeLongvarchar_QNAME = new QName("", "longvarchar");
    private final static QName _SingleValColTypeBlob_QNAME = new QName("", "blob");
    private final static QName _SingleValColTypeChar_QNAME = new QName("", "char");
    private final static QName _SingleValColTypeTime_QNAME = new QName("", "time");
    private final static QName _SingleValColTypeDecimal_QNAME = new QName("", "decimal");
    private final static QName _TransTypeUpdateRow_QNAME = new QName("", "updateRow");
    private final static QName _TransTypeDeleteRow_QNAME = new QName("", "deleteRow");
    private final static QName _TransTypeInsertRow_QNAME = new QName("", "insertRow");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.poc.demo.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SingleValColType }
     * 
     */
    public SingleValColType createSingleValColType() {
        return new SingleValColType();
    }

    /**
     * Create an instance of {@link UpdateValColType }
     * 
     */
    public UpdateValColType createUpdateValColType() {
        return new UpdateValColType();
    }

    /**
     * Create an instance of {@link UpdateValColType.Xml }
     * 
     */
    public UpdateValColType.Xml createUpdateValColTypeXml() {
        return new UpdateValColType.Xml();
    }

    /**
     * Create an instance of {@link UpdateValColType.Dbclob }
     * 
     */
    public UpdateValColType.Dbclob createUpdateValColTypeDbclob() {
        return new UpdateValColType.Dbclob();
    }

    /**
     * Create an instance of {@link UpdateValColType.Clob }
     * 
     */
    public UpdateValColType.Clob createUpdateValColTypeClob() {
        return new UpdateValColType.Clob();
    }

    /**
     * Create an instance of {@link UpdateValColType.Blob }
     * 
     */
    public UpdateValColType.Blob createUpdateValColTypeBlob() {
        return new UpdateValColType.Blob();
    }

    /**
     * Create an instance of {@link UpdateValColType.Rowid }
     * 
     */
    public UpdateValColType.Rowid createUpdateValColTypeRowid() {
        return new UpdateValColType.Rowid();
    }

    /**
     * Create an instance of {@link UpdateValColType.Longvargraphic }
     * 
     */
    public UpdateValColType.Longvargraphic createUpdateValColTypeLongvargraphic() {
        return new UpdateValColType.Longvargraphic();
    }

    /**
     * Create an instance of {@link UpdateValColType.Vargraphic }
     * 
     */
    public UpdateValColType.Vargraphic createUpdateValColTypeVargraphic() {
        return new UpdateValColType.Vargraphic();
    }

    /**
     * Create an instance of {@link UpdateValColType.Graphic }
     * 
     */
    public UpdateValColType.Graphic createUpdateValColTypeGraphic() {
        return new UpdateValColType.Graphic();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitlongvarchar }
     * 
     */
    public UpdateValColType.Bitlongvarchar createUpdateValColTypeBitlongvarchar() {
        return new UpdateValColType.Bitlongvarchar();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitvarchar }
     * 
     */
    public UpdateValColType.Bitvarchar createUpdateValColTypeBitvarchar() {
        return new UpdateValColType.Bitvarchar();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitchar }
     * 
     */
    public UpdateValColType.Bitchar createUpdateValColTypeBitchar() {
        return new UpdateValColType.Bitchar();
    }

    /**
     * Create an instance of {@link UpdateValColType.Longvarchar }
     * 
     */
    public UpdateValColType.Longvarchar createUpdateValColTypeLongvarchar() {
        return new UpdateValColType.Longvarchar();
    }

    /**
     * Create an instance of {@link UpdateValColType.Varchar }
     * 
     */
    public UpdateValColType.Varchar createUpdateValColTypeVarchar() {
        return new UpdateValColType.Varchar();
    }

    /**
     * Create an instance of {@link UpdateValColType.Char }
     * 
     */
    public UpdateValColType.Char createUpdateValColTypeChar() {
        return new UpdateValColType.Char();
    }

    /**
     * Create an instance of {@link UpdateValColType.Timestamp }
     * 
     */
    public UpdateValColType.Timestamp createUpdateValColTypeTimestamp() {
        return new UpdateValColType.Timestamp();
    }

    /**
     * Create an instance of {@link UpdateValColType.Time }
     * 
     */
    public UpdateValColType.Time createUpdateValColTypeTime() {
        return new UpdateValColType.Time();
    }

    /**
     * Create an instance of {@link UpdateValColType.Date }
     * 
     */
    public UpdateValColType.Date createUpdateValColTypeDate() {
        return new UpdateValColType.Date();
    }

    /**
     * Create an instance of {@link UpdateValColType.Decfloat }
     * 
     */
    public UpdateValColType.Decfloat createUpdateValColTypeDecfloat() {
        return new UpdateValColType.Decfloat();
    }

    /**
     * Create an instance of {@link UpdateValColType.Decimal }
     * 
     */
    public UpdateValColType.Decimal createUpdateValColTypeDecimal() {
        return new UpdateValColType.Decimal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Double }
     * 
     */
    public UpdateValColType.Double createUpdateValColTypeDouble() {
        return new UpdateValColType.Double();
    }

    /**
     * Create an instance of {@link UpdateValColType.Real }
     * 
     */
    public UpdateValColType.Real createUpdateValColTypeReal() {
        return new UpdateValColType.Real();
    }

    /**
     * Create an instance of {@link UpdateValColType.Float }
     * 
     */
    public UpdateValColType.Float createUpdateValColTypeFloat() {
        return new UpdateValColType.Float();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bigint }
     * 
     */
    public UpdateValColType.Bigint createUpdateValColTypeBigint() {
        return new UpdateValColType.Bigint();
    }

    /**
     * Create an instance of {@link UpdateValColType.Integer }
     * 
     */
    public UpdateValColType.Integer createUpdateValColTypeInteger() {
        return new UpdateValColType.Integer();
    }

    /**
     * Create an instance of {@link UpdateValColType.Smallint }
     * 
     */
    public UpdateValColType.Smallint createUpdateValColTypeSmallint() {
        return new UpdateValColType.Smallint();
    }

    /**
     * Create an instance of {@link LobType }
     * 
     */
    public LobType createLobType() {
        return new LobType();
    }

    /**
     * Create an instance of {@link MsgType }
     * 
     */
    public MsgType createMsgType() {
        return new MsgType();
    }

    /**
     * Create an instance of {@link AddColumnType }
     * 
     */
    public AddColumnType createAddColumnType() {
        return new AddColumnType();
    }

    /**
     * Create an instance of {@link UpdateRowType }
     * 
     */
    public UpdateRowType createUpdateRowType() {
        return new UpdateRowType();
    }

    /**
     * Create an instance of {@link ErrorRptType }
     * 
     */
    public ErrorRptType createErrorRptType() {
        return new ErrorRptType();
    }

    /**
     * Create an instance of {@link SingleValRowType }
     * 
     */
    public SingleValRowType createSingleValRowType() {
        return new SingleValRowType();
    }

    /**
     * Create an instance of {@link ColSchemaType }
     * 
     */
    public ColSchemaType createColSchemaType() {
        return new ColSchemaType();
    }

    /**
     * Create an instance of {@link LoadDoneRcvdType }
     * 
     */
    public LoadDoneRcvdType createLoadDoneRcvdType() {
        return new LoadDoneRcvdType();
    }

    /**
     * Create an instance of {@link HeartbeatType }
     * 
     */
    public HeartbeatType createHeartbeatType() {
        return new HeartbeatType();
    }

    /**
     * Create an instance of {@link TransType }
     * 
     */
    public TransType createTransType() {
        return new TransType();
    }

    /**
     * Create an instance of {@link SubSchemaType }
     * 
     */
    public SubSchemaType createSubSchemaType() {
        return new SubSchemaType();
    }

    /**
     * Create an instance of {@link RowOpType }
     * 
     */
    public RowOpType createRowOpType() {
        return new RowOpType();
    }

    /**
     * Create an instance of {@link SubDeactivatedType }
     * 
     */
    public SubDeactivatedType createSubDeactivatedType() {
        return new SubDeactivatedType();
    }

    /**
     * Create an instance of {@link SingleValColType.Smallint }
     * 
     */
    public SingleValColType.Smallint createSingleValColTypeSmallint() {
        return new SingleValColType.Smallint();
    }

    /**
     * Create an instance of {@link SingleValColType.Integer }
     * 
     */
    public SingleValColType.Integer createSingleValColTypeInteger() {
        return new SingleValColType.Integer();
    }

    /**
     * Create an instance of {@link SingleValColType.Bigint }
     * 
     */
    public SingleValColType.Bigint createSingleValColTypeBigint() {
        return new SingleValColType.Bigint();
    }

    /**
     * Create an instance of {@link SingleValColType.Float }
     * 
     */
    public SingleValColType.Float createSingleValColTypeFloat() {
        return new SingleValColType.Float();
    }

    /**
     * Create an instance of {@link SingleValColType.Real }
     * 
     */
    public SingleValColType.Real createSingleValColTypeReal() {
        return new SingleValColType.Real();
    }

    /**
     * Create an instance of {@link SingleValColType.Double }
     * 
     */
    public SingleValColType.Double createSingleValColTypeDouble() {
        return new SingleValColType.Double();
    }

    /**
     * Create an instance of {@link SingleValColType.Decimal }
     * 
     */
    public SingleValColType.Decimal createSingleValColTypeDecimal() {
        return new SingleValColType.Decimal();
    }

    /**
     * Create an instance of {@link SingleValColType.Decfloat }
     * 
     */
    public SingleValColType.Decfloat createSingleValColTypeDecfloat() {
        return new SingleValColType.Decfloat();
    }

    /**
     * Create an instance of {@link SingleValColType.Date }
     * 
     */
    public SingleValColType.Date createSingleValColTypeDate() {
        return new SingleValColType.Date();
    }

    /**
     * Create an instance of {@link SingleValColType.Time }
     * 
     */
    public SingleValColType.Time createSingleValColTypeTime() {
        return new SingleValColType.Time();
    }

    /**
     * Create an instance of {@link SingleValColType.Timestamp }
     * 
     */
    public SingleValColType.Timestamp createSingleValColTypeTimestamp() {
        return new SingleValColType.Timestamp();
    }

    /**
     * Create an instance of {@link SingleValColType.Char }
     * 
     */
    public SingleValColType.Char createSingleValColTypeChar() {
        return new SingleValColType.Char();
    }

    /**
     * Create an instance of {@link SingleValColType.Varchar }
     * 
     */
    public SingleValColType.Varchar createSingleValColTypeVarchar() {
        return new SingleValColType.Varchar();
    }

    /**
     * Create an instance of {@link SingleValColType.Longvarchar }
     * 
     */
    public SingleValColType.Longvarchar createSingleValColTypeLongvarchar() {
        return new SingleValColType.Longvarchar();
    }

    /**
     * Create an instance of {@link SingleValColType.Bitchar }
     * 
     */
    public SingleValColType.Bitchar createSingleValColTypeBitchar() {
        return new SingleValColType.Bitchar();
    }

    /**
     * Create an instance of {@link SingleValColType.Bitvarchar }
     * 
     */
    public SingleValColType.Bitvarchar createSingleValColTypeBitvarchar() {
        return new SingleValColType.Bitvarchar();
    }

    /**
     * Create an instance of {@link SingleValColType.Bitlongvarchar }
     * 
     */
    public SingleValColType.Bitlongvarchar createSingleValColTypeBitlongvarchar() {
        return new SingleValColType.Bitlongvarchar();
    }

    /**
     * Create an instance of {@link SingleValColType.Graphic }
     * 
     */
    public SingleValColType.Graphic createSingleValColTypeGraphic() {
        return new SingleValColType.Graphic();
    }

    /**
     * Create an instance of {@link SingleValColType.Vargraphic }
     * 
     */
    public SingleValColType.Vargraphic createSingleValColTypeVargraphic() {
        return new SingleValColType.Vargraphic();
    }

    /**
     * Create an instance of {@link SingleValColType.Longvargraphic }
     * 
     */
    public SingleValColType.Longvargraphic createSingleValColTypeLongvargraphic() {
        return new SingleValColType.Longvargraphic();
    }

    /**
     * Create an instance of {@link SingleValColType.Rowid }
     * 
     */
    public SingleValColType.Rowid createSingleValColTypeRowid() {
        return new SingleValColType.Rowid();
    }

    /**
     * Create an instance of {@link SingleValColType.Blob }
     * 
     */
    public SingleValColType.Blob createSingleValColTypeBlob() {
        return new SingleValColType.Blob();
    }

    /**
     * Create an instance of {@link SingleValColType.Clob }
     * 
     */
    public SingleValColType.Clob createSingleValColTypeClob() {
        return new SingleValColType.Clob();
    }

    /**
     * Create an instance of {@link SingleValColType.Dbclob }
     * 
     */
    public SingleValColType.Dbclob createSingleValColTypeDbclob() {
        return new SingleValColType.Dbclob();
    }

    /**
     * Create an instance of {@link SingleValColType.Xml }
     * 
     */
    public SingleValColType.Xml createSingleValColTypeXml() {
        return new SingleValColType.Xml();
    }

    /**
     * Create an instance of {@link UpdateValColType.Xml.BeforeVal }
     * 
     */
    public UpdateValColType.Xml.BeforeVal createUpdateValColTypeXmlBeforeVal() {
        return new UpdateValColType.Xml.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Xml.AfterVal }
     * 
     */
    public UpdateValColType.Xml.AfterVal createUpdateValColTypeXmlAfterVal() {
        return new UpdateValColType.Xml.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Dbclob.BeforeVal }
     * 
     */
    public UpdateValColType.Dbclob.BeforeVal createUpdateValColTypeDbclobBeforeVal() {
        return new UpdateValColType.Dbclob.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Dbclob.AfterVal }
     * 
     */
    public UpdateValColType.Dbclob.AfterVal createUpdateValColTypeDbclobAfterVal() {
        return new UpdateValColType.Dbclob.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Clob.BeforeVal }
     * 
     */
    public UpdateValColType.Clob.BeforeVal createUpdateValColTypeClobBeforeVal() {
        return new UpdateValColType.Clob.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Clob.AfterVal }
     * 
     */
    public UpdateValColType.Clob.AfterVal createUpdateValColTypeClobAfterVal() {
        return new UpdateValColType.Clob.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Blob.BeforeVal }
     * 
     */
    public UpdateValColType.Blob.BeforeVal createUpdateValColTypeBlobBeforeVal() {
        return new UpdateValColType.Blob.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Blob.AfterVal }
     * 
     */
    public UpdateValColType.Blob.AfterVal createUpdateValColTypeBlobAfterVal() {
        return new UpdateValColType.Blob.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Rowid.BeforeVal }
     * 
     */
    public UpdateValColType.Rowid.BeforeVal createUpdateValColTypeRowidBeforeVal() {
        return new UpdateValColType.Rowid.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Rowid.AfterVal }
     * 
     */
    public UpdateValColType.Rowid.AfterVal createUpdateValColTypeRowidAfterVal() {
        return new UpdateValColType.Rowid.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Longvargraphic.BeforeVal }
     * 
     */
    public UpdateValColType.Longvargraphic.BeforeVal createUpdateValColTypeLongvargraphicBeforeVal() {
        return new UpdateValColType.Longvargraphic.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Longvargraphic.AfterVal }
     * 
     */
    public UpdateValColType.Longvargraphic.AfterVal createUpdateValColTypeLongvargraphicAfterVal() {
        return new UpdateValColType.Longvargraphic.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Vargraphic.BeforeVal }
     * 
     */
    public UpdateValColType.Vargraphic.BeforeVal createUpdateValColTypeVargraphicBeforeVal() {
        return new UpdateValColType.Vargraphic.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Vargraphic.AfterVal }
     * 
     */
    public UpdateValColType.Vargraphic.AfterVal createUpdateValColTypeVargraphicAfterVal() {
        return new UpdateValColType.Vargraphic.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Graphic.BeforeVal }
     * 
     */
    public UpdateValColType.Graphic.BeforeVal createUpdateValColTypeGraphicBeforeVal() {
        return new UpdateValColType.Graphic.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Graphic.AfterVal }
     * 
     */
    public UpdateValColType.Graphic.AfterVal createUpdateValColTypeGraphicAfterVal() {
        return new UpdateValColType.Graphic.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitlongvarchar.BeforeVal }
     * 
     */
    public UpdateValColType.Bitlongvarchar.BeforeVal createUpdateValColTypeBitlongvarcharBeforeVal() {
        return new UpdateValColType.Bitlongvarchar.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitlongvarchar.AfterVal }
     * 
     */
    public UpdateValColType.Bitlongvarchar.AfterVal createUpdateValColTypeBitlongvarcharAfterVal() {
        return new UpdateValColType.Bitlongvarchar.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitvarchar.BeforeVal }
     * 
     */
    public UpdateValColType.Bitvarchar.BeforeVal createUpdateValColTypeBitvarcharBeforeVal() {
        return new UpdateValColType.Bitvarchar.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitvarchar.AfterVal }
     * 
     */
    public UpdateValColType.Bitvarchar.AfterVal createUpdateValColTypeBitvarcharAfterVal() {
        return new UpdateValColType.Bitvarchar.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitchar.BeforeVal }
     * 
     */
    public UpdateValColType.Bitchar.BeforeVal createUpdateValColTypeBitcharBeforeVal() {
        return new UpdateValColType.Bitchar.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bitchar.AfterVal }
     * 
     */
    public UpdateValColType.Bitchar.AfterVal createUpdateValColTypeBitcharAfterVal() {
        return new UpdateValColType.Bitchar.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Longvarchar.BeforeVal }
     * 
     */
    public UpdateValColType.Longvarchar.BeforeVal createUpdateValColTypeLongvarcharBeforeVal() {
        return new UpdateValColType.Longvarchar.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Longvarchar.AfterVal }
     * 
     */
    public UpdateValColType.Longvarchar.AfterVal createUpdateValColTypeLongvarcharAfterVal() {
        return new UpdateValColType.Longvarchar.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Varchar.BeforeVal }
     * 
     */
    public UpdateValColType.Varchar.BeforeVal createUpdateValColTypeVarcharBeforeVal() {
        return new UpdateValColType.Varchar.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Varchar.AfterVal }
     * 
     */
    public UpdateValColType.Varchar.AfterVal createUpdateValColTypeVarcharAfterVal() {
        return new UpdateValColType.Varchar.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Char.BeforeVal }
     * 
     */
    public UpdateValColType.Char.BeforeVal createUpdateValColTypeCharBeforeVal() {
        return new UpdateValColType.Char.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Char.AfterVal }
     * 
     */
    public UpdateValColType.Char.AfterVal createUpdateValColTypeCharAfterVal() {
        return new UpdateValColType.Char.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Timestamp.BeforeVal }
     * 
     */
    public UpdateValColType.Timestamp.BeforeVal createUpdateValColTypeTimestampBeforeVal() {
        return new UpdateValColType.Timestamp.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Timestamp.AfterVal }
     * 
     */
    public UpdateValColType.Timestamp.AfterVal createUpdateValColTypeTimestampAfterVal() {
        return new UpdateValColType.Timestamp.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Time.BeforeVal }
     * 
     */
    public UpdateValColType.Time.BeforeVal createUpdateValColTypeTimeBeforeVal() {
        return new UpdateValColType.Time.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Time.AfterVal }
     * 
     */
    public UpdateValColType.Time.AfterVal createUpdateValColTypeTimeAfterVal() {
        return new UpdateValColType.Time.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Date.BeforeVal }
     * 
     */
    public UpdateValColType.Date.BeforeVal createUpdateValColTypeDateBeforeVal() {
        return new UpdateValColType.Date.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Date.AfterVal }
     * 
     */
    public UpdateValColType.Date.AfterVal createUpdateValColTypeDateAfterVal() {
        return new UpdateValColType.Date.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Decfloat.BeforeVal }
     * 
     */
    public UpdateValColType.Decfloat.BeforeVal createUpdateValColTypeDecfloatBeforeVal() {
        return new UpdateValColType.Decfloat.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Decfloat.AfterVal }
     * 
     */
    public UpdateValColType.Decfloat.AfterVal createUpdateValColTypeDecfloatAfterVal() {
        return new UpdateValColType.Decfloat.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Decimal.BeforeVal }
     * 
     */
    public UpdateValColType.Decimal.BeforeVal createUpdateValColTypeDecimalBeforeVal() {
        return new UpdateValColType.Decimal.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Decimal.AfterVal }
     * 
     */
    public UpdateValColType.Decimal.AfterVal createUpdateValColTypeDecimalAfterVal() {
        return new UpdateValColType.Decimal.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Double.BeforeVal }
     * 
     */
    public UpdateValColType.Double.BeforeVal createUpdateValColTypeDoubleBeforeVal() {
        return new UpdateValColType.Double.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Double.AfterVal }
     * 
     */
    public UpdateValColType.Double.AfterVal createUpdateValColTypeDoubleAfterVal() {
        return new UpdateValColType.Double.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Real.BeforeVal }
     * 
     */
    public UpdateValColType.Real.BeforeVal createUpdateValColTypeRealBeforeVal() {
        return new UpdateValColType.Real.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Real.AfterVal }
     * 
     */
    public UpdateValColType.Real.AfterVal createUpdateValColTypeRealAfterVal() {
        return new UpdateValColType.Real.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Float.BeforeVal }
     * 
     */
    public UpdateValColType.Float.BeforeVal createUpdateValColTypeFloatBeforeVal() {
        return new UpdateValColType.Float.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Float.AfterVal }
     * 
     */
    public UpdateValColType.Float.AfterVal createUpdateValColTypeFloatAfterVal() {
        return new UpdateValColType.Float.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bigint.BeforeVal }
     * 
     */
    public UpdateValColType.Bigint.BeforeVal createUpdateValColTypeBigintBeforeVal() {
        return new UpdateValColType.Bigint.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Bigint.AfterVal }
     * 
     */
    public UpdateValColType.Bigint.AfterVal createUpdateValColTypeBigintAfterVal() {
        return new UpdateValColType.Bigint.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Integer.BeforeVal }
     * 
     */
    public UpdateValColType.Integer.BeforeVal createUpdateValColTypeIntegerBeforeVal() {
        return new UpdateValColType.Integer.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Integer.AfterVal }
     * 
     */
    public UpdateValColType.Integer.AfterVal createUpdateValColTypeIntegerAfterVal() {
        return new UpdateValColType.Integer.AfterVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Smallint.BeforeVal }
     * 
     */
    public UpdateValColType.Smallint.BeforeVal createUpdateValColTypeSmallintBeforeVal() {
        return new UpdateValColType.Smallint.BeforeVal();
    }

    /**
     * Create an instance of {@link UpdateValColType.Smallint.AfterVal }
     * 
     */
    public UpdateValColType.Smallint.AfterVal createUpdateValColTypeSmallintAfterVal() {
        return new UpdateValColType.Smallint.AfterVal();
    }

    /**
     * Create an instance of {@link LobType.Blob }
     * 
     */
    public LobType.Blob createLobTypeBlob() {
        return new LobType.Blob();
    }

    /**
     * Create an instance of {@link LobType.Clob }
     * 
     */
    public LobType.Clob createLobTypeClob() {
        return new LobType.Clob();
    }

    /**
     * Create an instance of {@link LobType.Dbclob }
     * 
     */
    public LobType.Dbclob createLobTypeDbclob() {
        return new LobType.Dbclob();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "msg")
    public JAXBElement<MsgType> createMsg(MsgType value) {
        return new JAXBElement<MsgType>(_Msg_QNAME, MsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Vargraphic.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Vargraphic.class)
    public JAXBElement<UpdateValColType.Vargraphic.BeforeVal> createUpdateValColTypeVargraphicBeforeVal(UpdateValColType.Vargraphic.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Vargraphic.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Vargraphic.BeforeVal.class, UpdateValColType.Vargraphic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Clob.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Clob.class)
    public JAXBElement<UpdateValColType.Clob.BeforeVal> createUpdateValColTypeClobBeforeVal(UpdateValColType.Clob.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Clob.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Clob.BeforeVal.class, UpdateValColType.Clob.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Blob.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Blob.class)
    public JAXBElement<UpdateValColType.Blob.BeforeVal> createUpdateValColTypeBlobBeforeVal(UpdateValColType.Blob.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Blob.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Blob.BeforeVal.class, UpdateValColType.Blob.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Float.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Float.class)
    public JAXBElement<UpdateValColType.Float.BeforeVal> createUpdateValColTypeFloatBeforeVal(UpdateValColType.Float.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Float.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Float.BeforeVal.class, UpdateValColType.Float.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Real.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Real.class)
    public JAXBElement<UpdateValColType.Real.BeforeVal> createUpdateValColTypeRealBeforeVal(UpdateValColType.Real.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Real.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Real.BeforeVal.class, UpdateValColType.Real.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Bigint.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Bigint.class)
    public JAXBElement<UpdateValColType.Bigint.BeforeVal> createUpdateValColTypeBigintBeforeVal(UpdateValColType.Bigint.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Bigint.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Bigint.BeforeVal.class, UpdateValColType.Bigint.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Date> createSingleValColTypeDate(SingleValColType.Date value) {
        return new JAXBElement<SingleValColType.Date>(_SingleValColTypeDate_QNAME, SingleValColType.Date.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Bitvarchar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bitvarchar", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Bitvarchar> createSingleValColTypeBitvarchar(SingleValColType.Bitvarchar value) {
        return new JAXBElement<SingleValColType.Bitvarchar>(_SingleValColTypeBitvarchar_QNAME, SingleValColType.Bitvarchar.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Dbclob }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dbclob", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Dbclob> createSingleValColTypeDbclob(SingleValColType.Dbclob value) {
        return new JAXBElement<SingleValColType.Dbclob>(_SingleValColTypeDbclob_QNAME, SingleValColType.Dbclob.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Bitchar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bitchar", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Bitchar> createSingleValColTypeBitchar(SingleValColType.Bitchar value) {
        return new JAXBElement<SingleValColType.Bitchar>(_SingleValColTypeBitchar_QNAME, SingleValColType.Bitchar.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Bitlongvarchar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bitlongvarchar", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Bitlongvarchar> createSingleValColTypeBitlongvarchar(SingleValColType.Bitlongvarchar value) {
        return new JAXBElement<SingleValColType.Bitlongvarchar>(_SingleValColTypeBitlongvarchar_QNAME, SingleValColType.Bitlongvarchar.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "integer", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Integer> createSingleValColTypeInteger(SingleValColType.Integer value) {
        return new JAXBElement<SingleValColType.Integer>(_SingleValColTypeInteger_QNAME, SingleValColType.Integer.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "float", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Float> createSingleValColTypeFloat(SingleValColType.Float value) {
        return new JAXBElement<SingleValColType.Float>(_SingleValColTypeFloat_QNAME, SingleValColType.Float.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Rowid }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rowid", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Rowid> createSingleValColTypeRowid(SingleValColType.Rowid value) {
        return new JAXBElement<SingleValColType.Rowid>(_SingleValColTypeRowid_QNAME, SingleValColType.Rowid.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Decfloat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "decfloat", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Decfloat> createSingleValColTypeDecfloat(SingleValColType.Decfloat value) {
        return new JAXBElement<SingleValColType.Decfloat>(_SingleValColTypeDecfloat_QNAME, SingleValColType.Decfloat.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Smallint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "smallint", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Smallint> createSingleValColTypeSmallint(SingleValColType.Smallint value) {
        return new JAXBElement<SingleValColType.Smallint>(_SingleValColTypeSmallint_QNAME, SingleValColType.Smallint.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Clob }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clob", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Clob> createSingleValColTypeClob(SingleValColType.Clob value) {
        return new JAXBElement<SingleValColType.Clob>(_SingleValColTypeClob_QNAME, SingleValColType.Clob.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Xml }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xml", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Xml> createSingleValColTypeXml(SingleValColType.Xml value) {
        return new JAXBElement<SingleValColType.Xml>(_SingleValColTypeXml_QNAME, SingleValColType.Xml.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Bigint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bigint", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Bigint> createSingleValColTypeBigint(SingleValColType.Bigint value) {
        return new JAXBElement<SingleValColType.Bigint>(_SingleValColTypeBigint_QNAME, SingleValColType.Bigint.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Graphic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "graphic", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Graphic> createSingleValColTypeGraphic(SingleValColType.Graphic value) {
        return new JAXBElement<SingleValColType.Graphic>(_SingleValColTypeGraphic_QNAME, SingleValColType.Graphic.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Timestamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timestamp", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Timestamp> createSingleValColTypeTimestamp(SingleValColType.Timestamp value) {
        return new JAXBElement<SingleValColType.Timestamp>(_SingleValColTypeTimestamp_QNAME, SingleValColType.Timestamp.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Longvargraphic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "longvargraphic", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Longvargraphic> createSingleValColTypeLongvargraphic(SingleValColType.Longvargraphic value) {
        return new JAXBElement<SingleValColType.Longvargraphic>(_SingleValColTypeLongvargraphic_QNAME, SingleValColType.Longvargraphic.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Vargraphic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vargraphic", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Vargraphic> createSingleValColTypeVargraphic(SingleValColType.Vargraphic value) {
        return new JAXBElement<SingleValColType.Vargraphic>(_SingleValColTypeVargraphic_QNAME, SingleValColType.Vargraphic.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "double", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Double> createSingleValColTypeDouble(SingleValColType.Double value) {
        return new JAXBElement<SingleValColType.Double>(_SingleValColTypeDouble_QNAME, SingleValColType.Double.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Varchar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "varchar", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Varchar> createSingleValColTypeVarchar(SingleValColType.Varchar value) {
        return new JAXBElement<SingleValColType.Varchar>(_SingleValColTypeVarchar_QNAME, SingleValColType.Varchar.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Real }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "real", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Real> createSingleValColTypeReal(SingleValColType.Real value) {
        return new JAXBElement<SingleValColType.Real>(_SingleValColTypeReal_QNAME, SingleValColType.Real.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Longvarchar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "longvarchar", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Longvarchar> createSingleValColTypeLongvarchar(SingleValColType.Longvarchar value) {
        return new JAXBElement<SingleValColType.Longvarchar>(_SingleValColTypeLongvarchar_QNAME, SingleValColType.Longvarchar.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Blob }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "blob", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Blob> createSingleValColTypeBlob(SingleValColType.Blob value) {
        return new JAXBElement<SingleValColType.Blob>(_SingleValColTypeBlob_QNAME, SingleValColType.Blob.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Char }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "char", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Char> createSingleValColTypeChar(SingleValColType.Char value) {
        return new JAXBElement<SingleValColType.Char>(_SingleValColTypeChar_QNAME, SingleValColType.Char.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Time }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Time> createSingleValColTypeTime(SingleValColType.Time value) {
        return new JAXBElement<SingleValColType.Time>(_SingleValColTypeTime_QNAME, SingleValColType.Time.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValColType.Decimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "decimal", scope = SingleValColType.class)
    public JAXBElement<SingleValColType.Decimal> createSingleValColTypeDecimal(SingleValColType.Decimal value) {
        return new JAXBElement<SingleValColType.Decimal>(_SingleValColTypeDecimal_QNAME, SingleValColType.Decimal.class, SingleValColType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Double.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Double.class)
    public JAXBElement<UpdateValColType.Double.BeforeVal> createUpdateValColTypeDoubleBeforeVal(UpdateValColType.Double.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Double.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Double.BeforeVal.class, UpdateValColType.Double.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Date.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Date.class)
    public JAXBElement<UpdateValColType.Date.BeforeVal> createUpdateValColTypeDateBeforeVal(UpdateValColType.Date.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Date.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Date.BeforeVal.class, UpdateValColType.Date.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Time.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Time.class)
    public JAXBElement<UpdateValColType.Time.BeforeVal> createUpdateValColTypeTimeBeforeVal(UpdateValColType.Time.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Time.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Time.BeforeVal.class, UpdateValColType.Time.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Graphic.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Graphic.class)
    public JAXBElement<UpdateValColType.Graphic.BeforeVal> createUpdateValColTypeGraphicBeforeVal(UpdateValColType.Graphic.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Graphic.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Graphic.BeforeVal.class, UpdateValColType.Graphic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Char.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Char.class)
    public JAXBElement<UpdateValColType.Char.BeforeVal> createUpdateValColTypeCharBeforeVal(UpdateValColType.Char.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Char.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Char.BeforeVal.class, UpdateValColType.Char.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Bitchar.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Bitchar.class)
    public JAXBElement<UpdateValColType.Bitchar.BeforeVal> createUpdateValColTypeBitcharBeforeVal(UpdateValColType.Bitchar.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Bitchar.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Bitchar.BeforeVal.class, UpdateValColType.Bitchar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Bitlongvarchar.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Bitlongvarchar.class)
    public JAXBElement<UpdateValColType.Bitlongvarchar.BeforeVal> createUpdateValColTypeBitlongvarcharBeforeVal(UpdateValColType.Bitlongvarchar.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Bitlongvarchar.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Bitlongvarchar.BeforeVal.class, UpdateValColType.Bitlongvarchar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Bitvarchar.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Bitvarchar.class)
    public JAXBElement<UpdateValColType.Bitvarchar.BeforeVal> createUpdateValColTypeBitvarcharBeforeVal(UpdateValColType.Bitvarchar.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Bitvarchar.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Bitvarchar.BeforeVal.class, UpdateValColType.Bitvarchar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "updateRow", scope = TransType.class)
    public JAXBElement<UpdateRowType> createTransTypeUpdateRow(UpdateRowType value) {
        return new JAXBElement<UpdateRowType>(_TransTypeUpdateRow_QNAME, UpdateRowType.class, TransType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValRowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deleteRow", scope = TransType.class)
    public JAXBElement<SingleValRowType> createTransTypeDeleteRow(SingleValRowType value) {
        return new JAXBElement<SingleValRowType>(_TransTypeDeleteRow_QNAME, SingleValRowType.class, TransType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleValRowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "insertRow", scope = TransType.class)
    public JAXBElement<SingleValRowType> createTransTypeInsertRow(SingleValRowType value) {
        return new JAXBElement<SingleValRowType>(_TransTypeInsertRow_QNAME, SingleValRowType.class, TransType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Timestamp.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Timestamp.class)
    public JAXBElement<UpdateValColType.Timestamp.BeforeVal> createUpdateValColTypeTimestampBeforeVal(UpdateValColType.Timestamp.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Timestamp.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Timestamp.BeforeVal.class, UpdateValColType.Timestamp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Decimal.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Decimal.class)
    public JAXBElement<UpdateValColType.Decimal.BeforeVal> createUpdateValColTypeDecimalBeforeVal(UpdateValColType.Decimal.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Decimal.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Decimal.BeforeVal.class, UpdateValColType.Decimal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Rowid.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Rowid.class)
    public JAXBElement<UpdateValColType.Rowid.BeforeVal> createUpdateValColTypeRowidBeforeVal(UpdateValColType.Rowid.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Rowid.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Rowid.BeforeVal.class, UpdateValColType.Rowid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Smallint.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Smallint.class)
    public JAXBElement<UpdateValColType.Smallint.BeforeVal> createUpdateValColTypeSmallintBeforeVal(UpdateValColType.Smallint.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Smallint.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Smallint.BeforeVal.class, UpdateValColType.Smallint.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Varchar.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Varchar.class)
    public JAXBElement<UpdateValColType.Varchar.BeforeVal> createUpdateValColTypeVarcharBeforeVal(UpdateValColType.Varchar.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Varchar.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Varchar.BeforeVal.class, UpdateValColType.Varchar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Decfloat.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Decfloat.class)
    public JAXBElement<UpdateValColType.Decfloat.BeforeVal> createUpdateValColTypeDecfloatBeforeVal(UpdateValColType.Decfloat.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Decfloat.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Decfloat.BeforeVal.class, UpdateValColType.Decfloat.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Dbclob.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Dbclob.class)
    public JAXBElement<UpdateValColType.Dbclob.BeforeVal> createUpdateValColTypeDbclobBeforeVal(UpdateValColType.Dbclob.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Dbclob.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Dbclob.BeforeVal.class, UpdateValColType.Dbclob.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Integer.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Integer.class)
    public JAXBElement<UpdateValColType.Integer.BeforeVal> createUpdateValColTypeIntegerBeforeVal(UpdateValColType.Integer.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Integer.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Integer.BeforeVal.class, UpdateValColType.Integer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Xml.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Xml.class)
    public JAXBElement<UpdateValColType.Xml.BeforeVal> createUpdateValColTypeXmlBeforeVal(UpdateValColType.Xml.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Xml.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Xml.BeforeVal.class, UpdateValColType.Xml.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Longvargraphic.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Longvargraphic.class)
    public JAXBElement<UpdateValColType.Longvargraphic.BeforeVal> createUpdateValColTypeLongvargraphicBeforeVal(UpdateValColType.Longvargraphic.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Longvargraphic.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Longvargraphic.BeforeVal.class, UpdateValColType.Longvargraphic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LobType.Clob }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clob", scope = LobType.class)
    public JAXBElement<LobType.Clob> createLobTypeClob(LobType.Clob value) {
        return new JAXBElement<LobType.Clob>(_SingleValColTypeClob_QNAME, LobType.Clob.class, LobType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LobType.Dbclob }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dbclob", scope = LobType.class)
    public JAXBElement<LobType.Dbclob> createLobTypeDbclob(LobType.Dbclob value) {
        return new JAXBElement<LobType.Dbclob>(_SingleValColTypeDbclob_QNAME, LobType.Dbclob.class, LobType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LobType.Blob }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "blob", scope = LobType.class)
    public JAXBElement<LobType.Blob> createLobTypeBlob(LobType.Blob value) {
        return new JAXBElement<LobType.Blob>(_SingleValColTypeBlob_QNAME, LobType.Blob.class, LobType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateValColType.Longvarchar.BeforeVal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beforeVal", scope = UpdateValColType.Longvarchar.class)
    public JAXBElement<UpdateValColType.Longvarchar.BeforeVal> createUpdateValColTypeLongvarcharBeforeVal(UpdateValColType.Longvarchar.BeforeVal value) {
        return new JAXBElement<UpdateValColType.Longvarchar.BeforeVal>(_UpdateValColTypeVargraphicBeforeVal_QNAME, UpdateValColType.Longvarchar.BeforeVal.class, UpdateValColType.Longvarchar.class, value);
    }

}
